name: Deploy Landing to GitHub Pages

on:
  push:
    tags:
      - "v*.*.*" # Trigger on version tags like v1.0.0

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run build
      - run: npm run deploy
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
